# coding: utf-8

"""
    ServicioConsumible

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import openapi_client
from openapi_client.models.problem_details import ProblemDetails  # noqa: E501
from openapi_client.rest import ApiException

class TestProblemDetails(unittest.TestCase):
    """ProblemDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ProblemDetails
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProblemDetails`
        """
        model = openapi_client.models.problem_details.ProblemDetails()  # noqa: E501
        if include_optional :
            return ProblemDetails(
                type = '', 
                title = '', 
                status = 56, 
                detail = '', 
                instance = ''
            )
        else :
            return ProblemDetails(
        )
        """

    def testProblemDetails(self):
        """Test ProblemDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
