# coding: utf-8

"""
    ServicioConsumible

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

import openapi_client
from openapi_client.api.solicitud_api import SolicitudApi  # noqa: E501
from openapi_client.rest import ApiException


class TestSolicitudApi(unittest.TestCase):
    """SolicitudApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.solicitud_api.SolicitudApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_solicitud_comprobar_solicitud_get(self):
        """Test case for solicitud_comprobar_solicitud_get

        """
        pass

    def test_solicitud_get_solicitudes_usuario_get(self):
        """Test case for solicitud_get_solicitudes_usuario_get

        """
        pass

    def test_solicitud_solicitar_post(self):
        """Test case for solicitud_solicitar_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
