# coding: utf-8

"""
    ServicioConsumible

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

import openapi_client
from openapi_client.api.email_api import EmailApi  # noqa: E501
from openapi_client.rest import ApiException


class TestEmailApi(unittest.TestCase):
    """EmailApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.email_api.EmailApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_email_post(self):
        """Test case for email_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
