# coding: utf-8

"""
    ServicioConsumible

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr, conlist

class Solicitud(BaseModel):
    """
    Solicitud
    """
    cantidades_iniciales: Optional[conlist(StrictInt)] = Field(None, alias="cantidadesIniciales")
    nombre_entidades: Optional[conlist(StrictStr)] = Field(None, alias="nombreEntidades")
    __properties = ["cantidadesIniciales", "nombreEntidades"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Solicitud:
        """Create an instance of Solicitud from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if cantidades_iniciales (nullable) is None
        # and __fields_set__ contains the field
        if self.cantidades_iniciales is None and "cantidades_iniciales" in self.__fields_set__:
            _dict['cantidadesIniciales'] = None

        # set to None if nombre_entidades (nullable) is None
        # and __fields_set__ contains the field
        if self.nombre_entidades is None and "nombre_entidades" in self.__fields_set__:
            _dict['nombreEntidades'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Solicitud:
        """Create an instance of Solicitud from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Solicitud.parse_obj(obj)

        _obj = Solicitud.parse_obj({
            "cantidades_iniciales": obj.get("cantidadesIniciales"),
            "nombre_entidades": obj.get("nombreEntidades")
        })
        return _obj


